### PR TITLE
Add example app & extend event with more keycode types & raw keycode value

### PR DESCRIPTION
**Pull request by iosifnicolae2**

### CODE REVIEW

**Comment by michalss** [comment]
merge it !

**Comment by CodeMinion** [comment]
Hi @michalss ,

Thank you for your comment. As stated in the original comment this branch makes the implementation too coupled to Android. Until that is addressed we won't be able to merge this branch. 

It has been a while since we heard from the original author so if we don't hear from them before the end of the week we will be closing this request.

**Comment by michalss** [comment]
ok thx so how we can handle other keys then ? Are you planning to do it for android pls ? Btw i do care about only android so far...

**Comment by CodeMinion** [comment]
The goal is to define a platform-independent set of keys so Flutter apps are agnostic to the underlaying platform @michalss .

Unfortunately, currently my time is being taking up by another initiative that does not involved TVs so I don't have a line of sight as to when I might be able to expand this.

**Pull request closed without merging**
